version: "3.8"
services:
    app:
        build: .
        container_name: appointment-planning-system-app
        restart: unless-stopped
        working_dir: /app
        volumes:
            - .:/var/www
            - .:/app
        ports:
            - "8001:8001"
        depends_on:
            - db
        networks:
            - appointment-planning-network

    db:
        image: mysql:8
        container_name: appointment-planning-system-db
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
        ports:
            - "3306:3306"
        networks:
            - appointment-planning-network
        volumes:
            - dbdata:/var/lib/mysql
networks:
    appointment-planning-network:
volumes:
    dbdata:
